/**
 * Zipkin API
 * Zipkin's v2 API currently includes a POST endpoint that can receive spans. 
 *
 * OpenAPI spec version: 2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Associates an event that explains latency with a timestamp. Unlike log statements, annotations are often codes. Ex. \"ws\" for WireSend  Zipkin v1 core annotations such as \"cs\" and \"sr\" have been replaced with Span.Kind, which interprets timestamp and duration. 
 */
export interface Annotation { 
    /**
     * Epoch **microseconds** of this event.  For example, 1502787600000000 corresponds to 2017-08-15 09:00 UTC  This value should be set directly by instrumentation, using the most precise value possible. For example, gettimeofday or multiplying epoch millis by 1000. 
     */
    timestamp: number;
    /**
     * Usually a short tag indicating an event, like \"error\"  While possible to add larger data, such as garbage collection details, low cardinality event names both keep the size of spans down and also are easy to search against. 
     */
    value: string;
}
