/**
 * Zipkin API
 * Zipkin's v2 API currently includes a POST endpoint that can receive spans. 
 *
 * OpenAPI spec version: 2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * The count of traced calls between services, or between a service and a broker.  The direction of the link is parent to child, and can be one of:  * client to server  * producer to broker  * broker to consumer  Note: This is related to span ID count between a sender and receiver, but there is nuance that makes it more difficult than counting unique span IDs. Ex. the parent or child might be uninstrumented: detected via the remote endpoint. There can also be scenarios where both sides are instrumented. Please use existing tools such as zipkin-dependencies to derive links as they avoid under or over counting. 
 */
export interface DependencyLink { 
    /**
     * The service name of the caller: client or message producer or broker.
     */
    parent: string;
    /**
     * The service name of the callee: server or message consumer or broker.
     */
    child: string;
    /**
     * Total traced calls made from the parent to the child.
     */
    callCount: number;
    /**
     * Total traced calls made from the parent to the child known to be in error.
     */
    errorCount?: number;
}
