/**
 * Zipkin API
 * Zipkin's v2 API currently includes a POST endpoint that can receive spans. 
 *
 * OpenAPI spec version: 2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * The network context of a node in the service graph
 */
export interface Endpoint { 
    /**
     * Lower-case label of this node in the service graph, such as \"favstar\". Leave absent if unknown.  This is a primary label for trace lookup and aggregation, so it should be intuitive and consistent. Many use a name from service discovery. 
     */
    serviceName?: string;
    /**
     * The text representation of the primary IPv4 address associated with this connection. Ex. 192.168.99.100 Absent if unknown. 
     */
    ipv4?: string;
    /**
     * The text representation of the primary IPv6 address associated with a connection. Ex. 2001:db8::c001 Absent if unknown.  Prefer using the ipv4 field for mapped addresses. 
     */
    ipv6?: string;
    /**
     * Depending on context, this could be a listen port or the client-side of a socket. Absent if unknown. Please don't set to zero. 
     */
    port?: number;
}
