/**
 * Zipkin API
 * Zipkin's v2 API currently includes a POST endpoint that can receive spans. 
 *
 * OpenAPI spec version: 2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Trace } from './trace';


export interface ListOfTraces extends Array<Trace> { 
}
