/**
 * Zipkin API
 * Zipkin's v2 API currently includes a POST endpoint that can receive spans. 
 *
 * OpenAPI spec version: 2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Adds context to a span, for search, viewing and analysis.  For example, a key \"your_app.version\" would let you lookup traces by version. A tag \"sql.query\" isn't searchable, but it can help in debugging when viewing a trace. 
 */
export interface Tags { 
  [key: string]: string;


}
