/**
 * Zipkin API
 * Zipkin's v2 API currently includes a POST endpoint that can receive spans. 
 *
 * OpenAPI spec version: 2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Span } from './span';


/**
 * List of spans who have the same trace ID.
 */
export interface Trace extends Array<Span> { 
}
